
"""create initial tables

Revision ID: 94595f13041c
Revises: 0001_create_initial_tables
Create Date: 2025-11-18 23:41:34.551769
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94595f13041c'
down_revision = '0001_create_initial_tables'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorio',
        sa.Column('id_relatorio', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('titulo', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id_relatorio')
    )

    op.create_table('expressoescorporal',
        sa.Column('id_expressao_c', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('intensidade', sa.Float(), nullable=True),
        sa.Column('frequencia', sa.Integer(), nullable=True),
        sa.Column('id_engajamento', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['id_engajamento'], ['engajamento_documento.id_engajamento'], ),
        sa.PrimaryKeyConstraint('id_expressao_c')
    )

    op.create_table('expressoesfaciais',
        sa.Column('id_expressao_f', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('intensidade', sa.Float(), nullable=True),
        sa.Column('frequencia', sa.Integer(), nullable=True),
        sa.Column('id_engajamento', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['id_engajamento'], ['engajamento_documento.id_engajamento'], ),
        sa.PrimaryKeyConstraint('id_expressao_f')
    )

    op.drop_table('expressoes_corporal')
    op.drop_table('expressoes_faciais')

    op.drop_constraint('fk_captura_frame_engajamento', 'captura_frame', type_='foreignkey')
    op.create_foreign_key(None, 'captura_frame', 'engajamento_documento', ['id_engajamento'], ['id_engajamento'])
    op.create_foreign_key(None, 'engajamento_documento', 'relatorio', ['id_relatorio'], ['id_relatorio'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'engajamento_documento', type_='foreignkey')
    op.drop_constraint(None, 'captura_frame', type_='foreignkey')
    op.create_foreign_key('fk_captura_frame_engajamento', 'captura_frame', 'engajamento_documento', ['id_engajamento'], ['id_engajamento'], ondelete='SET NULL')
    op.create_table('expressoes_faciais',
    sa.Column('id_expressao_f', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('intensidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frequencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_engajamento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_engajamento'], ['engajamento_documento.id_engajamento'], name='fk_expressoes_faciais_engajamento', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_expressao_f', name='expressoes_faciais_pkey')
    )
    op.create_table('expressoes_corporal',
    sa.Column('id_expressao_c', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('intensidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frequencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_engajamento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_engajamento'], ['engajamento_documento.id_engajamento'], name='fk_expressoes_corporal_engajamento', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_expressao_c', name='expressoes_corporal_pkey')
    )
    op.drop_table('expressoesfaciais')
    op.drop_table('expressoescorporal')
    op.drop_table('relatorio')
    # ### end Alembic commands ###
